[mypy]
warn_redundant_casts = True
warn_unused_ignores = True
show_error_codes = True
plugins = numpy.typing.mypy_plugin
allow_redefinition = True
no_implicit_optional = True
disable_error_code = import-untyped, import-not-found
python_version = 3.11
exclude = (?x)(exp\/.*\.py$|test-.*\.py$|misc\/data\/.*.py$)